/********************************************************************************
 *  Module: Port
 *
 *	File Name: PORT_PBconfig.h
 *
 * Description: Post-Compile Configuration Header file for STM32f103C6T6 Microcontroller - Port Driver.
 *
 * Author: Mostafa Amr
 *
 *******************************************************************************/

#include "PORT.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration = {
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,           /*PA0*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA1*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA2*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA3*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA4*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA5*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA6*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA7*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA8*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA9*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA10*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA11*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA12*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA13*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA14*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PA15*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB0*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB1*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB2*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB3*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB4*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB5*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB6*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB7*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB8*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB9*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB10*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB11*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB12*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB13*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB14*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PB15*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC0*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC1*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC2*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC3*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC4*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC5*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC6*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC7*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC8*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC9*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC10*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC11*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC12*/
											 PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC13*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC14*/
                                             PORT_DEFAULT_MODE_VALUE, PORT_DEFAULT_DIRECTION_VALUE, PORT_DEFAULT_LEVEL_VALUE,   PORT_DEFAULT_DIRECTION_CHANGEABLE, PORT_DEFAULT_MODE_CHANGEABLE, PORT_DEFAULT_INTERNAL_PULL_UP, PORT_DEFAULT_INTERNAL_PULL_DOWN,          /*PC15*/
                                           };

